const provinces = [
  { name: 'Toàn quốc', value: 0 },
  { name: 'An Giang', value: 1 },
  { name: 'Bà Rịa - Vũng Tàu', value: 2 },
  { name: 'Bạc Liêu', value: 3 },
  { name: 'Bắc Kạn', value: 4 },
  { name: 'Bắc Giang', value: 5 },
  { name: 'Bắc Ninh', value: 6 },
  { name: 'Bến Tre', value: 7 },
  { name: 'Bình Dương', value: 8 },
  { name: 'Bình Định', value: 9 },
  { name: 'Bình Phước', value: 10 },
  { name: 'Bình Thuận', value: 11 },
  { name: 'Cà Mau', value: 12 },
  { name: 'Cao Bằng', value: 13 },
  { name: 'TP. Cần Thơ', value: 14 },
  { name: 'TP. Đà Nẵng', value: 15 },
  { name: 'Đắk Lắk', value: 16 },
  { name: 'Đắk Nông', value: 17 },
  { name: 'Điện Biên', value: 18 },
  { name: 'Đồng Nai', value: 19 },
  { name: 'Đồng Tháp', value: 20 },
  { name: 'Gia Lai', value: 21 },
  { name: 'Hà Giang', value: 22 },
  { name: 'Hà Nam', value: 23 },
  { name: 'TP. Hà Nội', value: 24 },
  { name: 'Hà Tĩnh', value: 25 },
  { name: 'Hải Dương', value: 26 },
  { name: 'TP. Hải Phòng', value: 27 },
  { name: 'Hòa Bình', value: 28 },
  { name: 'TP. Hồ Chí Minh', value: 29 },
  { name: 'Hậu Giang', value: 30 },
  { name: 'Hưng Yên', value: 31 },
  { name: 'Khánh Hòa', value: 32 },
  { name: 'Kiên Giang', value: 33 },
  { name: 'Kon Tum', value: 34 },
  { name: 'Lai Châu', value: 35 },
  { name: 'Lào Cai', value: 36 },
  { name: 'Lạng Sơn', value: 37 },
  { name: 'Lâm Đồng', value: 38 },
  { name: 'Long An', value: 39 },
  { name: 'Nam Định', value: 40 },
  { name: 'Nghệ An', value: 41 },
  { name: 'Ninh Bình', value: 42 },
  { name: 'Ninh Thuận', value: 43 },
  { name: 'Phú Thọ', value: 44 },
  { name: 'Phú Yên', value: 45 },
  { name: 'Quảng Bình', value: 46 },
  { name: 'Quảng Nam', value: 47 },
  { name: 'Quảng Ngãi', value: 48 },
  { name: 'Quảng Ninh', value: 49 },
  { name: 'Quảng Trị', value: 50 },
  { name: 'Sóc Trăng', value: 51 },
  { name: 'Sơn La', value: 52 },
  { name: 'Tây Ninh', value: 53 },
  { name: 'Thái Bình', value: 54 },
  { name: 'Thái Nguyên', value: 55 },
  { name: 'Thanh Hóa', value: 56 },
  { name: 'Thừa Thiên – Huế', value: 57 },
  { name: 'Tiền Giang', value: 58 },
  { name: 'Trà Vinh', value: 59 },
  { name: 'Tuyên Quang', value: 60 },
  { name: 'Vĩnh Long', value: 61 },
  { name: 'Vĩnh Phúc', value: 62 },
  { name: 'Yên Bái', value: 63 },
]

export default provinces
